//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookPlatformWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public Books()
        {
            this.Complaints = new HashSet<Complaints>();
            this.ReadingLists = new HashSet<ReadingLists>();
            this.Reviews = new HashSet<Reviews>();
            this.UnfreezeRequests = new HashSet<UnfreezeRequests>();
            this.Genres = new HashSet<Genres>();
        }
    
        public int BookID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public int AuthorID { get; set; }
        public bool IsFrozen { get; set; }
        public string FreezeReason { get; set; }
        public string CoverPath { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Complaints> Complaints { get; set; }
        public virtual ICollection<ReadingLists> ReadingLists { get; set; }
        public virtual ICollection<Reviews> Reviews { get; set; }
        public virtual ICollection<UnfreezeRequests> UnfreezeRequests { get; set; }
        public virtual ICollection<Genres> Genres { get; set; }
    }
}
