//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookPlatformWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints
    {
        public int ComplaintID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public string Reason { get; set; }
        public System.DateTime ComplaintDate { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Reviews Reviews { get; set; }
        public virtual Users Users { get; set; }
    }
}
