//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookPlatformWPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookPlatformEntities1 : DbContext
    {
        public BookPlatformEntities1()
            : base("name=BookPlatformEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Books> Books { get; set; }
        public DbSet<Complaints> Complaints { get; set; }
        public DbSet<Genres> Genres { get; set; }
        public DbSet<ReadingLists> ReadingLists { get; set; }
        public DbSet<Reviews> Reviews { get; set; }
        public DbSet<RoleRequests> RoleRequests { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<UnfreezeRequests> UnfreezeRequests { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
