//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookPlatformWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public Reviews()
        {
            this.Complaints = new HashSet<Complaints>();
        }
    
        public int ReviewID { get; set; }
        public int UserID { get; set; }
        public int BookID { get; set; }
        public string ReviewText { get; set; }
        public int Rating { get; set; }
        public System.DateTime ReviewDate { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual ICollection<Complaints> Complaints { get; set; }
        public virtual Users Users { get; set; }
    }
}
