//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookPlatformWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleRequests
    {
        public int RequestID { get; set; }
        public int UserID { get; set; }
        public System.DateTime RequestDate { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
